title: "Ayda Haydarpour"
description: "Cloud & Security • AWS • Systems"
url: "https://ayda-hdp.github.io"
baseurl: "/aydahaydarpour.github.io"   # project site = repo name, leading slash

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"
markdown: kramdown
search: false

plugins:
  - jekyll-include-cache

include:
  - _pages

# Header navigation — include baseurl for a project site
nav:
  - title: "Home"
    url: /aydahaydarpour.github.io/
  - title: "Projects"
    url: /aydahaydarpour.github.io/#projects
  - title: "Media"
    url: /aydahaydarpour.github.io/#media
  - title: "Contact"
    url: mailto:aydahaydarpour@gmail.com

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults: consistent left sidebar, narrower reading width
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      classes: ""
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: single
      author_profile: true
      classes: ""
      share: false
      related: false

author:
  name: "Ayda Haydarpour"
  avatar:
  bio: "Computer Science senior specializing in cloud architecture, cybersecurity, and systems development. Experienced in AWS, security best practices, and building end-to-end technical solutions that blend reliability, scalability, and real-world impact."
  skills:
    - "**Cloud Services:** AWS (EC2, S3, RDS, VPC, Route 53, CloudFront, IAM, CloudWatch, Auto Scaling, Load Balancing)"
    - "**Security & Networking:** IAM policies & access control, network security, VPNs & firewalls, data encryption & hashing, monitoring & logging, Security+ best practices"
    - "**Programming & Scripting:** Python, Java, C, Bash, JavaScript, HTML/CSS, SQL"
    - "**Tools & Platforms:** Linux, Git & GitHub, Wireshark, system monitoring tools"

# Optional previews (using your existing image for now)
og_image: /assets/images/diagram.png   # fine for social previews today
logo: 

atom_feed:
  hide: true

footer:
  links: []
