title: "Ayda Haydarpour"
description: "Cloud & Security • AWS • Systems"
url: "https://ayda-hdp.github.io"
baseurl: ""   # user site = empty

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"
markdown: kramdown
search: false

plugins:
  - jekyll-include-cache

include:
  - _pages

# Header navigation
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /portfolio/
  - title: "Media"
    url: /media/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults: consistent left sidebar, narrower reading width
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      classes: ""
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: single
      author_profile: true
      classes: ""
      share: false
      related: false

author:
  name: "Ayda Haydarpour"
  avatar:
  bio: "Computer Science senior specializing in cloud architecture, cybersecurity, and systems development. Experienced in AWS, security best practices, and building end-to-end technical solutions that blend reliability, scalability, and real-world impact."
  skills:
    - "**Cloud Services:** AWS (EC2, S3, RDS, VPC, Route 53, CloudFront, IAM, CloudWatch, Auto Scaling, Load Balancing)"
    - "**Security & Networking:** IAM policies & access control, network security, VPNs & firewalls, data encryption & hashing, monitoring & logging, Security+ best practices"
    - "**Programming & Scripting:** Python, Java, C, Bash, JavaScript, HTML/CSS, SQL"
    - "**Tools & Platforms:** Linux, Git & GitHub, Wireshark, system monitoring tools"

atom_feed:
  hide: true

footer:
  links: []
