title: "Ayda Haydarpour"
description: "Cloud & Security • AWS • Systems"
url: "https://ayda-hdp.github.io"
baseurl: "/aydahaydarpour.github.io"   # must match repo name exactly

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"
markdown: kramdown
search: false

plugins:
  - jekyll-include-cache

include:
  - _pages

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      classes: wide
      share: false
      related: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide

author:
  name: "Ayda Haydarpour"
  avatar:
  bio: "Computer Science senior specializing in cloud architecture, cybersecurity, and systems development."
