title: "Ayda Haydarpour"
description: "Cloud & Security • AWS • Systems"
url: "https://<your-username>.github.io"   # if this repo is your main site
baseurl: ""                                 # "" for main site; "/<repo-name>" for a project site

# Minimal Mistakes theme (remote theme = zero theme files in your repo)
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"

# Keep it simple (no blog/search)
search: false
markdown: kramdown

# Required by Minimal Mistakes includes
plugins:
  - jekyll-include-cache

# Where your standalone pages live
include:
  - _pages

# ---- Portfolio collection (your projects) ----
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults for pages + portfolio entries
defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      classes: wide
      share: false
      related: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide

# Optional author block (not shown unless you enable author_profile on a page)
author:
  name: "Ayda Haydarpour"
  avatar:
  bio:
